### ISSUE TITLE
Community driven roadmap

### ISSUE THREAD

**Issue by Saalvage** [doctest/doctest#600]
I think that instead of focusing on interesting features or those that would look good on the box, doctest should instead focus on implementing features that people actually using doctest would benefit from on a frequent basis.
This is why I'm moving the roadmap into this issue, where everyone will be able to comment their thoughts!
This should mostly be a place to share rough ideas that are not concrete enough to justify an issue of their own and in general discuss the future development of doctest.

**Before 2.5**:
- [ ] Clean up all the docs, benchmarks and whatnot

**2.5**:
- [ ] Splitting the two monolithic doctest files up into more managable chunks (while keeping it single header for release)
- [ ] Generic container and STL stringification

**Comment by wendajiang** [comment]
Can #685 be add to the roadmap?

**Comment by jokervTv** [comment]
Is there any information about MPI here?

**Comment by USwampertor** [comment]
Are there any plans for microbenchmarking such as Catch2

**Comment by mitchgrout** [comment]
v2.5 has now been released, which addresses a few of the points. I'll keep this issue alive for the time being, but feel free to raise feature request issues, and reference here if desired.

I'll give v2.5 some time to simmer before kicking off v2.6 which will hopefully come with some enhancements to our matcher system.
